# Generated by Django 6.0.3 on 2026-04-02 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_categoria', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CompraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compra', models.CharField(max_length=30, unique=True)),
                ('fecha_compra', models.DateField()),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FlujoCajaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'INGRESO'), ('EGRESO', 'EGRESO')], max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('venta_id', models.BigIntegerField(blank=True, null=True)),
                ('compra_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flujo_caja',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, db_column='categoria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='clientes_app.categoriamodel')),
                ('proveedor', models.ForeignKey(blank=True, db_column='proveedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes_app.proveedormodel')),
            ],
            options={
                'db_table': 'productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compra', models.ForeignKey(db_column='compra_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='clientes_app.compramodel')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='clientes_app.productomodel')),
            ],
            options={
                'db_table': 'detalle_compras',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='compramodel',
            name='proveedor',
            field=models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='clientes_app.proveedormodel'),
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, to='clientes_app.rolmodel')),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MensajeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100)),
                ('contenido', models.TextField(max_length=1000)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(db_column='destinatario_id', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='clientes_app.usuariomodel')),
                ('remitente', models.ForeignKey(db_column='remitente_id', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='clientes_app.usuariomodel')),
            ],
            options={
                'db_table': 'mensajes',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.AddField(
            model_name='compramodel',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='clientes_app.usuariomodel'),
        ),
        migrations.CreateModel(
            name='VentaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venta', models.CharField(max_length=20, unique=True)),
                ('fecha_venta', models.DateField()),
                ('tipo_documento', models.CharField(max_length=30)),
                ('forma_pago', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes_app.clientemodel')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes_app.usuariomodel')),
            ],
            options={
                'db_table': 'ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='clientes_app.productomodel')),
                ('venta', models.ForeignKey(db_column='venta_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='clientes_app.ventamodel')),
            ],
            options={
                'db_table': 'detalle_ventas',
                'ordering': ['id'],
            },
        ),
    ]
