# Generated by Django 6.0.3 on 2026-04-06 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0002_passwordresettokenmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'modulos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RolPermisoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver', models.BooleanField(default=True)),
                ('puede_crear', models.BooleanField(default=False)),
                ('puede_editar', models.BooleanField(default=False)),
                ('puede_eliminar', models.BooleanField(default=False)),
                ('modulo', models.ForeignKey(db_column='modulo_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='clientes_app.modulomodel')),
                ('rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='clientes_app.rolmodel')),
            ],
            options={
                'db_table': 'roles_permisos',
                'ordering': ['id'],
                'unique_together': {('rol', 'modulo')},
            },
        ),
    ]
